In [4]:
SSG_Directory = '/home/jovyan/shared/projects/Sep_Iter/Metadata/Data/SSG_Reports/'
Navicat_Directory = '/home/jovyan/shared/projects/Sep_Iter/Metadata/Data/Navicat/'

In [5]:
import os
import pandas as pd
import warnings

In [6]:
warnings.filterwarnings("ignore", category=UserWarning, module='openpyxl')
excel_files = [f for f in os.listdir(SSG_Directory) if f.endswith('.xlsx')]
df_list = []

for file in excel_files:
    file_path = os.path.join(SSG_Directory, file)
    df = pd.read_excel(file_path)
    df_list.append(df)
    
combined_df = pd.concat(df_list, ignore_index=True)
combined_df = combined_df.dropna(subset=["Document Name"])
# Standardize 'Document Name' to lower case for comparison
combined_df['Document Name'] = combined_df['Document Name'].str.lower().str.replace(r"\.{2,}(?=pdf)", ".", regex=True)

combined_df['OMNI Fund ID'] = combined_df['OMNI Fund ID'].astype('Int64')
combined_df

,SPI Fund Sector,Omni GP,Omni Fund,OMNI Fund ID,# of Items,Doc Type,Document Name,Doc Link,Folder Path,Created Date,Effective Date
0,Venture Capital,Total,NaN,10119,232.0,Ltr,2024.03.27.distribution.breakdown.wp growth.ny...,https://stepstone.sharepoint.com/SPAR/API/API ...,https://stepstone.sharepoint.com/SPAR/API/API ...,2024-07-19 10:43:42,NaT
1,Venture Capital,Wavemaker Partners (fka Siemer Ventures),Total,10252,1.0,Rpt,2024.03.31.rpt.wavemaker pacific iv.pdf,https://stepstone.sharepoint.com/SPAR/API/API ...,https://stepstone.sharepoint.com/SPAR/API/API ...,2024-06-25 19:13:51,NaT
2,Venture Capital,Wavemaker Partners (fka Siemer Ventures),"Wavemaker Pacific IV, L.P.",10252,1.0,Rpt,2024.03.31.rpt.wavemaker pacific iv.pdf,https://stepstone.sharepoint.com/SPAR/API/API ...,https://stepstone.sharepoint.com/SPAR/API/API ...,2024-06-25 19:13:51,NaT
3,Venture Capital,The Venture City,Total,12340,2.0,Rpt,2024.03.31.rpt.venture city i.pdf,https://stepstone.sharepoint.com/SPAR/API/API ...,https://stepstone.sharepoint.com/SPAR/API/API ...,2024-07-10 20:30:10,NaT
4,Venture Capital,The Venture City,"The Venture City Fund II, L.P.",12341,1.0,Rpt,2024.03.31.rpt.venture city ii.pdf,https://stepstone.sharepoint.com/SPAR/API/API ...,https://stepstone.sharepoint.com/SPAR/API/API ...,2024-07-10 20:24:56,NaT
...,...,...,...,...,...,...,...,...,...,...,...
39074,Buyout,TPG Capital,"TPG Partners V, L.P.",1535,1.0,Rpt,2022.06.30.rpt.tpg v.pdf,https://stepstone.sharepoint.com/SPAR/API/API ...,https://stepstone.sharepoint.com/SPAR/API/API ...,2022-08-09 19:25:17,NaT
39075,Buyout,TPG Capital,"TPG Partners VI, L.P.",1536,1.0,Rpt,2022.06.30.rpt.tpg vi.pdf,https://stepstone.sharepoint.com/SPAR/API/API ...,https://stepstone.sharepoint.com/SPAR/API/API ...,2022-08-09 19:22:27,NaT
39076,Buyout,TPG Capital,"TPG Partners VII, L.P.",2111,1.0,Rpt,2022.06.30.rpt.tpg vii.pdf,https://stepstone.sharepoint.com/SPAR/API/API ...,https://stepstone.sharepoint.com/SPAR/API/API ...,2022-08-09 23:59:31,NaT
39077,Buyout,TPG Capital,"TPG Partners VIII, L.P.",4652,1.0,Rpt,2022.06.30.rpt.tpg viii.pdf,https://stepstone.sharepoint.com/SPAR/API/API ...,https://stepstone.sharepoint.com/SPAR/API/API ...,2022-09-06 13:26:48,NaT
39082,Buyout,Warburg Pincus,"Warburg Pincus Financial Sector, L.P.",3583,1.0,Rpt,2022.06.30.rpt.wp fin i.pdf,https://stepstone.sharepoint.com/SPAR/API/API ...,https://stepstone.sharepoint.com/SPAR/API/API ...,2022-09-20 23:56:48,NaT

In [7]:
Navicat_Directory = '/home/jovyan/shared/projects/Sep_Iter/Metadata/Data/Navicat/'
excel_files = [f for f in os.listdir(Navicat_Directory) if f.endswith('.xlsx')]
df_list_1=[]
for file in excel_files:
    filepath = os.path.join(Navicat_Directory, file)
    df1 = pd.read_excel(filepath)
    df_list_1.append(df1)
navicat_df = pd.concat(df_list_1, ignore_index=True)

#
navicat_df['omni_fund_id'] = navicat_df['omni_fund_id'].astype('Int64')
navicat_df

,GPID,GP_Name,FundID,Fund_Name,omni_fund_id,omni_fund_name,Vintage,Fund_Size_USD,Asset_Class,Sector,Sub_Sector,Region,Country,primary_country
0,1,.406 Ventures Management,1,.406 Ventures I,1984,"Point 406 Ventures I, L.P.",2006.0,167.00000,Private Equity,Venture Capital,Early Stage,North America,United States,1
1,10183,BBH 1818 Buyout,8,1818 Fund II,3347,"The 1818 Fund II, L.P.",1993.0,475.00000,Private Equity,Buyout,Middle Buyout,North America,United States,1
2,6,360Â° Capital Partners,18,360Â° Capital One S.C.A,1885,360 Capital One S.C.A. - SICAR,2006.0,127.16200,Private Equity,Venture Capital,Early Stage,Europe,Luxembourg,1
3,9224,3i Eurofund,23,3i Eurofund I,78,"3i Europartners, L.P.",1993.0,383.14650,Private Equity,Buyout,Middle Buyout,Europe,United Kingdom,1
4,9224,3i Eurofund,24,3i Eurofund II,76,"3i Europartners II, L.P.",1997.0,728.86290,Private Equity,Buyout,Middle Buyout,Europe,United Kingdom,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47777,6914,Pemberton Capital Advisors,53371,Pemberton Strategic Credit Fund IV,13971,"Pemberton Strategic Credit Fund IV, L.P.",2024.0,1.00000,Private Debt,Corporate,Opportunistic Lending,Europe,United Kingdom,1
47778,25694,Fulcrum Ventures,53375,Fulcrum Ventures Fund I,<NA>,NaN,2024.0,30.00000,Private Equity,Venture Capital,Early Stage,North America,United States,1
47779,16813,Koinos Capital,53381,Italian Founders Fund,<NA>,NaN,2023.0,56.59572,Private Equity,Venture Capital,Early Stage,Europe,Italy,1
47780,25436,MGR Capital,53384,MGR SPV,13978,MGR SPV,2024.0,61.58000,Private Equity,Venture Capital,Late Stage,North America,United States,1
47781,6734,Altimeter Capital,53385,Altimeter Lightmatter Co-Invest (Lightmatter),13982,Altimeter Lightmatter Co-Invest (Lightmatter),2024.0,25.00000,Private Equity,Other,Co-Investments,North America,United States,1

In [8]:
import pandas as pd

# Assuming combined_df and navicat_df are already defined

# Merge to add the 'Document Name' from combined_df to navicat_df
merged_df = pd.merge(navicat_df, combined_df[['OMNI Fund ID', 'Document Name']], left_on='omni_fund_id', right_on='OMNI Fund ID', how='right',indicator=True)
merged_df[merged_df["_merge"]=='left_only']

df3=merged_df[merged_df["_merge"]=='both']

# Group by 'Document Name' and aggregate 'omni_fund_id' to see unique values per document
grouped = df3.groupby('Document Name')['omni_fund_id'].agg(lambda x: set(x)).reset_index()

# Identify where there are multiple unique 'omni_fund_id's per 'Document Name'
multiple_fund_ids = grouped[grouped['omni_fund_id'].apply(len) > 1]

# If you want to see the full rows from the original DataFrame for these cases
if not multiple_fund_ids.empty:
    # Expanding the set of 'omni_fund_id' back to individual rows for clarity
    expanded_rows = df[df['Document Name'].isin(multiple_fund_ids['Document Name'])]
else:
    expanded_rows = pd.DataFrame()

print(expanded_rows)

Empty DataFrame
Columns: [SPI Fund Sector, Omni GP, Omni Fund, OMNI Fund ID, # of Items, Doc Type, Document Name, Doc Link, Folder Path, Created Date]
Index: []

In [9]:
# Assuming combined_df and navicat_df are already defined

# Merge to add the 'Document Name' from combined_df to navicat_df
merged_df = pd.merge(navicat_df, combined_df[['OMNI Fund ID', 'Document Name']], left_on='omni_fund_id', right_on='OMNI Fund ID', how='right',indicator=True)
main_df = merged_df.drop_duplicates('Document Name', keep='last')

In [10]:
import re
# Function to extract date
def extract_date(doc_name):
    # Match both YYYY.MM.DD and QX.YYYY formats
    match = re.search(r'(\d{4}\.\d{2}\.\d{2})|(Q\d\.\d{4})', doc_name)
    if match:
        return match.group(0)
    return None

# Apply the function to extract dates
main_df['Date'] = main_df['Document Name'].apply(extract_date)

/tmp/ipykernel_94904/179201683.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['Date'] = main_df['Document Name'].apply(extract_date)

In [12]:
from datetime import datetime

def get_quarter_end_date(date):
    if date is None:
        return None

    if isinstance(date, str) and 'Q' in date:
        year = int(date.split('.')[1])
        quarter = int(date.split('.')[0][1])
    else:
        date_obj = datetime.strptime(date, '%Y.%m.%d')
        year = date_obj.year
        month = date_obj.month
        if month <= 3:
            quarter = 1
        elif month <= 6:
            quarter = 2
        elif month <= 9:
            quarter = 3
        else:
            quarter = 4

    # Return the quarter end date
    if quarter == 1:
        return f'{year}.03.31'
    elif quarter == 2:
        return f'{year}.06.30'
    elif quarter == 3:
        return f'{year}.09.30'
    elif quarter == 4:
        return f'{year}.12.31'

# Apply the function to the "date" column
main_df['quarter_end_date'] = main_df['Date'].apply(get_quarter_end_date)
import pandas as pd

main_df

/tmp/ipykernel_94904/2402863613.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  main_df['quarter_end_date'] = main_df['Date'].apply(get_quarter_end_date)

,GPID,GP_Name,FundID,Fund_Name,omni_fund_id,omni_fund_name,Vintage,Fund_Size_USD,Asset_Class,Sector,Sub_Sector,Region,Country,primary_country,OMNI Fund ID,Document Name,_merge,Date,quarter_end_date
2,5720,Wavemaker Partners (fka Siemer Ventures),42475,Wavemaker SEA Fund IV,10252,"Wavemaker Pacific IV, L.P.",2021.0,136.069625,Private Equity,Venture Capital,Early Stage,North America,United States,1,10252,2024.03.31.rpt.wavemaker pacific iv.pdf,both,2024.03.31,2024.03.31
4,13712,The Venture City,39063,The Venture City Fund II,12341,"The Venture City Fund II, L.P.",2020.0,120.000000,Private Equity,Venture Capital,Early Stage,North America,United States,1,12341,2024.03.31.rpt.venture city ii.pdf,both,2024.03.31,2024.03.31
5,13712,The Venture City,33345,The Venture City Fund I,12340,"The Venture City Fund I, L.P.",2017.0,50.000000,Private Equity,Venture Capital,Early Stage,North America,United States,1,12340,2024.03.31.rpt.venture city i.pdf,both,2024.03.31,2024.03.31
7,3263,Valor Equity Partners,42247,Valor Equity Partners VI,10706,"Valor Equity Partners VI, L.P.",2022.0,2350.000000,Private Equity,Venture Capital,Expansion,North America,United States,1,10706,2024.03.31.rpt.valor vi.pdf,both,2024.03.31,2024.03.31
8,3263,Valor Equity Partners,35468,Valor Equity Partners Fund V,6354,"Valor Equity Partners V, L.P.",2020.0,1700.000000,Private Equity,Venture Capital,Balanced,North America,United States,1,6354,2024.03.31.rpt.valor v.pdf,both,2024.03.31,2024.03.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21782,3493,TPG Capital,8266,Texas Pacific Group Partners V,1535,"TPG Partners V, L.P.",2006.0,15372.000000,Private Equity,Buyout,Global Buyout,North America,United States,1,1535,2022.06.30.rpt.tpg v.pdf,both,2022.06.30,2022.06.30
21783,3493,TPG Capital,9946,TPG Partners VI,1536,"TPG Partners VI, L.P.",2008.0,18873.000000,Private Equity,Buyout,Global Buyout,North America,United States,1,1536,2022.06.30.rpt.tpg vi.pdf,both,2022.06.30,2022.06.30
21784,3493,TPG Capital,19584,TPG Partners VII,2111,"TPG Partners VII, L.P.",2015.0,10495.060000,Private Equity,Buyout,Global Buyout,North America,United States,1,2111,2022.06.30.rpt.tpg vii.pdf,both,2022.06.30,2022.06.30
21785,3493,TPG Capital,29534,TPG Partners VIII,4652,"TPG Partners VIII, L.P.",2019.0,11200.000000,Private Equity,Buyout,Global Buyout,North America,United States,1,4652,2022.06.30.rpt.tpg viii.pdf,both,2022.06.30,2022.06.30
21786,11026,Warburg Pincus Financial,27819,Warburg Pincus Financial Sector Fund,3583,"Warburg Pincus Financial Sector, L.P.",2018.0,2457.000000,Private Equity,Buyout,Global Buyout,North America,United States,1,3583,2022.06.30.rpt.wp fin i.pdf,both,2022.06.30,2022.06.30

In [13]:
import pandas as pd

# Assuming main_df is your DataFrame

# Exporting to a CSV file with a full file path including the file name
output_file_path = '/home/jovyan/shared/projects/Sep_Iter/Metadata/Data/Metadata_Final/metadata_final.csv'  # Specify your desired file path and name
main_df.to_csv(output_file_path, index=False)  # index=False to exclude row numbers in the output file